global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-prometheus:9187']

  - job_name: 'litestar'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'minio-cluster'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['minio:9000']

  - job_name: 'minio-bucket'
    metrics_path: /minio/v2/metrics/bucket
    static_configs:
      - targets: ['minio:9000']
  