global:
  scrape_interval: 5m

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-prometheus:9187']

  - job_name: 'litestar'
    scheme: https
    static_configs:
      - targets: ['api.pokinder.com']
