global:
  scrape_interval: 1h

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-prometheus:9187']

  - job_name: 'litestar'
    static_configs:
      - targets: ['backend:8000']
